// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support multiple common env var names and provide safe defaults
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? import.meta.env.VITE_PUBLIC_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY ?? import.meta.env.VITE_SUPABASE_KEY ?? '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Guard access to `localStorage` (can be undefined during SSR or build)
const storage = typeof window !== 'undefined' && typeof window.localStorage !== 'undefined' ? window.localStorage : undefined;

// Create a top-level variable and export it (cannot `export` inside blocks)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _supabase: any;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: storage as unknown as typeof localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} else {
  // Avoid calling `createClient` with empty values (it throws). Provide a no-op proxy
  const handler: ProxyHandler<any> = {
    get(_target, prop) {
      return (..._args: any[]) => {
        // eslint-disable-next-line no-console
        console.warn(`Supabase not configured: attempted to access "${String(prop)}"`);
        return Promise.resolve(null);
      };
    }
  };

  _supabase = new Proxy({}, handler);
}

export const supabase = _supabase as ReturnType<typeof createClient<Database>>;